data:
  # Escolha entre 'csv' ou 'sklearn'
  source_type: "sklearn"
  
  # Nome do dataset se source_type for 'sklearn' (iris, wine, etc.)
  dataset_name: "iris"
  
  # Caminho do dataset se source_type for 'csv'
  filepath: "data/dataset.csv"
  
  random_state: 42

model:
  k_min: 2 # Mínimo de clusters a serem testados
  k_max: 20 # Máximo de clusters a serem testados
  init: "k-means++" # método de inicialização dos centros dos clusters
  n_init: 20 # Número de vezes que o algoritmo será executado com diferentes centros iniciais
  max_iter: 400 # Número máximo de iterações do algoritmo

visualization:
  style: "seaborn-v0_8-darkgrid"
  palette: "plasma"